# User Credentials
ACCESS_TOKEN = "1304900984-xsnLZGKvzbKyFFOUUH1Dy2UCAOz4nwOPfuCMwFE"
ACCESS_TOKEN_SECRET = "nh5FcJpXvji1IhWXoMhswXJq4lvGKljXhJiohypD85ZvO"
CONSUMER_KEY = "tJI3CmJtYLtH8ilnvMDR8N0qM"
CONSUMER_SECRET = "SQnZRLrnvr6CYab1yzfScVJnmwxQaOUaJjaYMFSEVMwJM46kgz"
